### ISSUE TITLE
Dynamic type created with this script is not properly deleted

### ISSUE THREAD

**Issue by Mantsje** [osisoft/sample-omf-temperature_sensor-python#2]
Hi,

Using the code from this example results in the dynamic type Temperature.Float that is created during the program not getting deleted from the PI system afterwards. I posed an [issue on PI](https://pisquare.osisoft.com/s/feed/0D51I00004jyQLQSA2) square about it with further explanations.

To resolve this issue simply change the uom to "degree Fahrenheit" rather than using the degree symbol. Then it will work for both creation and deletion.

Cheers

**Comment by derekendres** [comment]
Sorry for not responding for a year+ on this, but thanks for the information we will look at updating this.
